In [5]:
# print working dir

import os
cwd = os. getcwd()
print("Current Working Directory:", cwd)

Current Working Directory: /home/go38zin/idp/CG-Mapping-Benchmark


In [8]:
import numpy as np

data_path = "./data/l-ala2_ttot=500ns_dt=0.5fs_nstxout=2000.npz"

dataset = np.load(data_path, allow_pickle=True)
dataset = dict(dataset)

In [9]:


print(dataset.keys())

dict_keys(['R', 'F', 'box', 'species', 'mask'])


In [15]:
for key, item in dataset.items():
    print(key + ": " + str(type(item)) + ", " + str(item.shape) + ", " + str(item.dtype))

R: <class 'numpy.ndarray'>, (500001, 22, 3), float32
F: <class 'numpy.ndarray'>, (500001, 22, 3), float32
box: <class 'numpy.ndarray'>, (500001, 3, 3), float64
species: <class 'numpy.ndarray'>, (500001, 22), int64
mask: <class 'numpy.ndarray'>, (500001, 22), bool


In [17]:
R = dataset["R"]
F = dataset["F"]
box = dataset["box"]
species = dataset["species"]
mask = dataset["mask"]

In [19]:
R

array([[[1.4150001 , 1.3750001 , 1.643     ],
        [1.409     , 1.268     , 1.6660002 ],
        [1.355     , 1.4370002 , 1.71      ],
        ...,
        [1.768     , 2.052     , 1.6520001 ],
        [1.7590001 , 2.0170002 , 1.8210001 ],
        [1.917     , 2.035     , 1.7290001 ]],

       [[1.4050001 , 1.424     , 1.8720001 ],
        [1.3030001 , 1.4360001 , 1.8450001 ],
        [1.417     , 1.332     , 1.9310001 ],
        ...,
        [1.748     , 1.9840001 , 1.7130002 ],
        [1.8800001 , 1.952     , 1.608     ],
        [1.7200001 , 2.002     , 1.5360001 ]],

       [[1.3570002 , 1.491     , 1.834     ],
        [1.281     , 1.5660001 , 1.8620001 ],
        [1.314     , 1.394     , 1.8320001 ],
        ...,
        [1.7650002 , 1.9770001 , 1.768     ],
        [1.893     , 1.9620001 , 1.6330003 ],
        [1.7290001 , 2.032     , 1.6110001 ]],

       ...,

       [[2.3740003 , 1.7450001 , 1.3310002 ],
        [2.4720001 , 1.728     , 1.2950001 ],
        [2.321     , 1

In [20]:
F

array([[[  406.2798  ,   887.9443  ,    36.18242 ],
        [  264.30054 ,   223.59341 ,   286.32687 ],
        [ -449.33185 ,  -451.03653 ,  -155.03502 ],
        ...,
        [ -195.82465 ,  -164.90817 ,   -82.597595],
        [  259.03528 ,  -160.15877 ,   275.45975 ],
        [  107.35634 ,  -236.70349 ,   489.69348 ]],

       [[ -635.6154  ,  -652.4363  ,   248.8193  ],
        [ -559.21844 ,  -298.60648 ,   -88.447754],
        [  234.26346 ,  -110.807846,  -601.3556  ],
        ...,
        [ -268.00995 ,  -162.12698 ,  -396.4886  ],
        [  342.34595 ,   182.25081 ,  -495.0903  ],
        [  180.48727 ,   345.82922 ,  -136.37196 ]],

       [[   51.454426, -1143.0471  ,   601.73816 ],
        [  282.159   ,  -247.6338  ,  -657.9237  ],
        [ -652.68854 ,  -412.5923  ,   331.77576 ],
        ...,
        [  604.152   ,  -135.79607 ,  -209.09698 ],
        [ -146.97263 ,   -20.207344,   210.50002 ],
        [  269.14096 ,   797.8331  ,  -406.45654 ]],

       ...,

      

In [21]:
box

array([[[3.27937, 0.     , 0.     ],
        [0.     , 3.27937, 0.     ],
        [0.     , 0.     , 3.27937]],

       [[3.27937, 0.     , 0.     ],
        [0.     , 3.27937, 0.     ],
        [0.     , 0.     , 3.27937]],

       [[3.27937, 0.     , 0.     ],
        [0.     , 3.27937, 0.     ],
        [0.     , 0.     , 3.27937]],

       ...,

       [[3.27937, 0.     , 0.     ],
        [0.     , 3.27937, 0.     ],
        [0.     , 0.     , 3.27937]],

       [[3.27937, 0.     , 0.     ],
        [0.     , 3.27937, 0.     ],
        [0.     , 0.     , 3.27937]],

       [[3.27937, 0.     , 0.     ],
        [0.     , 3.27937, 0.     ],
        [0.     , 0.     , 3.27937]]], shape=(500001, 3, 3))

In [24]:
species[:5,]

array([[6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 1, 1],
       [6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 1, 1],
       [6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 1, 1],
       [6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 1, 1],
       [6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 6, 1, 1, 1, 6, 8, 7, 1, 6, 1, 1, 1]])

In [26]:
for line in species:
    if not (line==species[0,]).all():
        print("found non equal:", line)